export default {
  body: document.getElementById('body'),
  searchInput: document.getElementById('search'),
  searchBtn: document.getElementById('button'),
  cityLabel: document.getElementById('city'),
  dateLabel: document.getElementById('dt'),
  descriptionLabel: document.getElementById('description'),
  windLabel: document.getElementById('wind'),
  humidityLabel: document.getElementById('humidity'),
  numLabel: document.getElementById('num'),
  forecastLabel: document.getElementById('forecast'),
  weatherIcon: document.getElementById('condition'),
  fahrenheitBtn: document.getElementById('fahrenheit'),
  celsiusBtn: document.getElementById('celsius'),
};
